services:
  vpack-server:
    build: .
    container_name: vpack_monitor
    ports:
      - "8001:8001"
      - "8889:8889"
      - "9997:9997"
    volumes:
      - ./recordings:/app/recordings
    restart: unless-stopped
